Ajout d’un lien de téléchargement des donnnées Fantoir
etalab/adresse.data.gouv.fr pull request #1098
Opened 2022-03-25 16:08 UTC by GllmR

Cette PR propose d’ajouter un lien permettant de télécharger les données Fantoir de la commune sélectionnée.
Cette fonctionnalité a été réclamée par certains partenaires.

- Ajout d’une fonction qui appelle la route `/api-fantoir/communes/[code_commune]/voies.csv`
- Ajout d’un lien vers le fichier CSV sur la page qui affiche les voies de la commune

### Capture : 

![image](https://user-images.githubusercontent.com/56537238/160618797-194a8fc4-678d-423a-833f-690005bee51e.png)

Fix #1085

2022-03-28 09:17 UTC, Maxine-Le-Pennec approved these changes

2022-03-29 07:19 UTC, tmerlier requested changes

2022-03-29 07:19 UTC, tmerlier commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +          <a href={getVoiesCSVFantoir(codeCommune)}>
L'appelle à une fonction ici est un peu trompeur. On peut y mettre directement l'URL je pense.

2022-03-29 07:25 UTC, tmerlier commented
Le lien de téléchargement pourrait éventuellement être plus visible ? Si c'est une fonctionnalité demandée par des utilisateurs, autant l'assumer pleinement en mettant un bouton peut-être ?

2022-03-29 12:48 UTC, tmerlier requested changes

2022-03-29 12:48 UTC, tmerlier commented on pages/fantoir/departement/[departement]/commune/[commune]/index.js
> +            href={`https://plateforme.adresse.data.gouv.fr/api-fantoir/communes/${codeCommune}/voies.csv`}
On peut tout de même laisser l'URL récupérée en dans l'environnement afin de permettre de la modifier en mode dev.

`export const API_BAN_URL = process.env.NEXT_PUBLIC_API_BAN_URL || 'https://plateforme.adresse.data.gouv.fr'`

2022-03-29 13:17 UTC, tmerlier approved these changes

2022-03-29 13:23 UTC, merged