Utilisation des routes dynamiques pour les pages /explore
etalab/adresse.data.gouv.fr pull request #710
Opened 2020-11-27 10:02 UTC by cedric-famibelle-pronzola

- Suppression de la gestion des routes  `/explore` par express
- `pages/explore/commune.js` devient -> `pages/explore/commune/[codeCommune]/index.js`
- `pages/explore/commune/voie.js` devient -> `pages/explore/commune/[codeCommune]/voie/[...additional].js`
- Adaptation du composant `Voie`aux nouvelles routes dynamiques : 
  - `components/explorer/voie/index.js`
  - `components/explorer/voie/map-container.js`

2020-11-27 10:43 UTC, jdesboeufs commented
Pas convaincu par le `...additionnal`. Pourquoi pas un simple paramètre comme pour le reste ?

2020-11-27 11:39 UTC, tmerlier requested changes

2020-11-27 11:39 UTC, tmerlier commented on components/explorer/voie/map-container.js
> +    const suffixe = feature && feature.properties.suffixe !== 'null' ? feature.properties.suffixe : null
`'null'` ?

2020-11-27 11:39 UTC, tmerlier commented on components/explorer/voie/index.js
> +    const {codeCommune, additional} = Router.query
Pourquoi `additional` ?

2020-11-27 12:28 UTC, cedric-famibelle-pronzola commented on components/explorer/voie/map-container.js
> +    const suffixe = feature && feature.properties.suffixe !== 'null' ? feature.properties.suffixe : null
quand il n'y a pas de suffixe, `feature.properties.suffixe` est égal à `"null"` en string

2020-12-29 16:04 UTC, jdesboeufs commented
Obsolète

2020-12-29 16:04 UTC, closed without merging