Mise à jour du validateur vers la version 1.2
etalab/adresse.data.gouv.fr pull request #759
Opened 2021-01-12 13:29 UTC by GllmR

- Passage en composants fonctionnels
- Modifications visuelles
- Modification du rapport de validation

2021-01-12 16:23 UTC, tmerlier requested changes

2021-01-12 16:23 UTC, tmerlier commented on components/bases-locales/validator/report/summary/issue-rows.js
> +  if (issuesRows > 0) {
Il serait préférable de gérer le problème de la manière inverse. C'est-à-dire avoir une condition qui gère le retour `null` immédiatement et un retour par défaut avec le composant.

Cependant pour ce cas-ci, le mieux serait que les colonnes qui n'ont pas d'erreur soit gérées par le parent à l'aide d'un filtre.

2021-01-12 16:23 UTC, tmerlier commented on components/bases-locales/validator/report/summary/line-value.js
> +  const issuesType = hasErrors ? 'error' : ''
Pas nécessaire.

2021-01-12 16:23 UTC, tmerlier commented on components/bases-locales/validator/report/summary/row.js
> +  const issuesCount = row._errors.length // + row._warnings.length
Commentaire oublié ?

2021-01-12 16:23 UTC, tmerlier commented on components/bases-locales/validator/report/summary/row.js
> +  const handleError = () => {
`useCallback`

2021-01-12 17:24 UTC, tmerlier commented
Attention si on dépose un fichier `csv` et ensuite un fichier d'un format non prit en charge, l'analyse du premier fichier reste affiché. Certainement un bug déjà présent en production…

2021-01-14 15:55 UTC, tmerlier requested changes

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/index.js
> +      setInProgress(false)
`setInProgress(false)` peut être appelé après le try/catch.

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/index.js
> +  })
Pourrait être un `useMemo`.

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/index.js
> +  })
Pourrait être un `useMemo`.

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/summary/row-issues.js
> +  profile: PropTypes.string.isRequired,
Améliorable avec un `oneOf` de la liste des profiles acceptés.

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/summary/row-issues.js
> +            <div key={err} className={`issue ${getValidationErrorSeverity(err, profile) === 'E' ? 'error' : 'warning'} ${field && field.errors && (field.errors.includes(err)) ? 'select' : ''}`}>
Pourrais être calculé en dehors du render afin d'améliorer la lisibilité du code.

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/summary/row.js
> +  const [showIssues, setShowIssues] = useState()
`useState(false)`

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/summary/row.js
> +            onHover={field => setField(field)}
` onHover={setField}`

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/summary/issue-rows.js
> +  }
Attention `handleClick` utilise une méthode du parent pour envoyer des props du parent. Tout pourrait donc se faire dans le parent.

2021-01-14 15:55 UTC, tmerlier commented on components/bases-locales/validator/report/summary/line-value.js
> +    <Fragment key={rawValue}>
`key` n'est pas utile ici.

2021-01-15 08:14 UTC, GllmR commented on components/bases-locales/validator/report/summary/line-value.js
> +    <Fragment key={rawValue}>
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

2021-01-18 10:47 UTC, tmerlier requested changes
Impossible de merger en l'état, la PR contient des modifications ne lui appartenant pas.

2021-01-18 10:47 UTC, tmerlier commented on components/bases-locales/validator/report/summary/issue-rows.js
> +  if (!issuesRows || issuesRows === 0) {
`issuesRows` sera toujours `true` sinon la ligne précédente aurait provoqué une erreur.

2021-01-18 11:04 UTC, tmerlier approved these changes

2021-02-17 13:50 UTC, jdesboeufs approved these changes

2021-02-17 13:54 UTC, merged