Marine/charte
etalab/adresse.data.gouv.fr pull request #770
Opened 2021-02-03 11:05 UTC by Marine-Le-Pennec

2021-02-03 14:32 UTC, tmerlier requested changes

2021-02-03 14:32 UTC, tmerlier commented on components/partner.js
> +      <div className='item-b'> {link ? <a href={link} target='_blank' rel='noreferrer' className='partner-link'><b>{name}</b></a> : <b>{name}</b>} </div>
Le `<a>` devrait contenir l'image et le nom afin que tout soit cliquable. Par ailleurs ajouter un effet au survole, comme par exemple le soulignement du texte, permettrait d'assurer un feedback pour l'utilisateur et lui faire comprendre que c'est une lien cliquable.

2021-02-03 14:32 UTC, tmerlier commented on components/partner.js
> +      <div className='item-a'>
Nom de classe trop générique. On pourrait utiliser `logo` et `name` par exemple.

2021-02-03 14:32 UTC, tmerlier commented on components/partners.js
> +        <Partner link='https://geo.compiegnois.fr/portail/' src='/images/logos/partners/Geocompiegnois.png' alt='partenaire geocompiegnois' name='GéoCompiégnois' height={35} width={286} />
Le champ `alt` a pour objectif de fournir un texte de remplacement dans le cas où l'image ne s'afficherait pas mais également comme aide à la navigation pour les personnes atteintes de cécité. 

Pour `IDéO BFC` il serait préférable de noter `alt='Logo partenaire IDéO Bourgogne-Franche-Comté'`

2021-02-03 14:32 UTC, tmerlier commented on pages/bases-locales/charte.js
> +            <Book style={{verticalAlign: 'bottom', marginRight: '5px'}} />
À remplacer par `<Download  />`

2021-02-03 14:32 UTC, tmerlier commented on pages/index.js
> +        <div style={{marginTop: '3em', textAlign: 'center'}} >
L'utilisation d'une classe améliorerai la lisibilité du code.

2021-02-03 15:36 UTC, tmerlier requested changes

2021-02-03 15:36 UTC, tmerlier commented on components/partner.js
> +    <a className='partner' href={link} target='_blank' rel='noreferrer'>
`link` n'est pas indiqué comme `isRequired`. Si jamais celui-ci est `null` le lien ne fonctionnerait pas. Dans notre cas, tous les partenaires ont un lien, il est donc inutile de conditionner le rendu du composant et `link` peut être `isRequired`.

2021-02-03 16:03 UTC, tmerlier approved these changes

2021-02-17 15:31 UTC, tmerlier submitted a review, later dismissed
La gestion des différents affichage d'un partenaires sont trop compliqués, on peut simplifier et alléger le code.

La propriété `services` des partenaires aurait à gagner à devenir une liste de string. Cela nous permettrait changer facilement la mise en forme en cas de besoin. Pour cet affichage sous forme de tag, il nous suffirait d'un léger traitement de la string qui supprime les espaces, remplace la premier caractère de chaque mot par sa majuscule et afficher un #.

2021-02-17 15:31 UTC, tmerlier commented on partners.json
> +        "link": "www.imagina-coworkingbalagna.fr",
https://www.imagina-coworkingbalagna.fr

2021-02-17 15:31 UTC, tmerlier commented on components/partner.js
> +            <button type='button' onClick={() => setIsDisplay(!isDisplay)}>{displayChevron()}</button></div>
Il serait plus confortable pour l'utilisateur de pourvoir cliquer sur la `div` `button-container` directement.

2021-02-17 15:31 UTC, tmerlier commented on components/partner.js
> +  }
Peut être fait directement dans le `render`.

2021-02-17 15:31 UTC, tmerlier commented on components/partner.js
> +    alt: PropTypes.string
Toutes ces props sont requises.

2021-02-17 15:31 UTC, tmerlier commented on components/partners.js
> +  })
Peut être fait dans le `render`.

2021-02-17 15:31 UTC, tmerlier commented on partners.json
> +        "subtitle": "PACA",
N'est pas utilisé.

2021-02-17 15:31 UTC, tmerlier commented on components/partner.js
> +        {isChartePage && <p className='name'><b><a href={link} target='_blank' rel='noreferrer'>{name}</a></b></p>}
`target='_blank' rel='noreferrer'` à supprimer. Ce comportement est fortement déprécié et ne doit être utilisé que s'il est justifié.

2021-02-17 15:31 UTC, tmerlier commented on pages/index.js
> +      <Section background='grey' title='Adoptez la Charte de la Base Adresse Locale et rejoignez les organismes partenaires'>
Il serait préférable d'afficher un fond blanc afin de ne pas voir le contour de certain logo. Les sections voisines pourraient être affichées en gris.

2021-02-17 15:31 UTC, tmerlier commented on pages/bases-locales/charte.js
> +          <a href='https://adresse.data.gouv.fr/data/docs/charte-bal-v1.0.pdf' target='_blank' rel='noreferrer'>
`target='_blank' rel='noreferrer'` à supprimer.

2021-02-18 21:27 UTC, jdesboeufs approved these changes

2021-02-18 21:29 UTC, merged