[WIP] Ajout des témoignages
etalab/adresse.data.gouv.fr pull request #771
Opened 2021-02-08 17:24 UTC by Marine-Le-Pennec

Première vérification de code par Théo avant validation par Sophie concernant le contenu.

2021-02-10 13:27 UTC, tmerlier requested changes

2021-02-10 13:27 UTC, tmerlier commented on components/temoignages.js
> +    return Date.parse(a.date) > Date.parse(b.date) ? -1 : (Date.parse(a.date) < Date.parse(b.date) ? 1 : 0)
Écriture trop complexe avec des ternaires imbriquées et le calcule de `Date.parse` est en doublon.
On peut améliorer ce code de cette façon:
```
 const dateA = Date.parse(a.date)
 const dateB = Date.parse(b.date)
 
if (dateA === dateB) {
   return 0
}

return dateA > dateB ? -1 : 1
```

2021-02-10 13:27 UTC, tmerlier commented on components/temoignages.js
> +            gap: 6em
Il manque un `;`

2021-02-10 16:29 UTC, tmerlier requested changes

2021-02-10 16:29 UTC, tmerlier commented on pages/bases-locales/temoignages.js
> +    <Page>
Il manque `title` et `description` qui sont cruciaux pour les métadonnées de la page.

2021-02-10 16:29 UTC, tmerlier commented on pages/bases-locales/temoignages.js
> +      <Head title='Bonnes pratiques des Bases Adresses Locales' icon={<MessageCircle size={56} />} />
Ce titre ne semble pas correspondre à l'objectif de la page qui est de recenser les témoignages.

2021-02-10 19:49 UTC, jdesboeufs commented on components/temoignage.js
> +      <style global jsx>{` // Issue en cours sur GH NextJS : impossible de passer la classe d'un composant Image en dehors d'une balise style jsx globale ===> https://github.com/vercel/next.js/issues
😍

2021-02-10 19:53 UTC, jdesboeufs commented on public/temoignages.json
> +[
Pourquoi mettre ce fichier dans `/public` ?
Il n'est jamais fetché, donc il pourrait être à la racine.

Néanmoins l'avoir dans `/public` permet de récupérer le JSON. Est-ce l'intention ?

2021-02-10 20:17 UTC, jdesboeufs commented on components/temoignages.js
> +    const dateA = new Date(a.date)
Inutile de transformer ces chaînes de caractères en `Date`, elles sont déjà comparables, et le format ISO 8601 simplifie les choses.
Ces deux lignes peuvent donc être supprimées.

2021-02-11 08:50 UTC, Marine-Le-Pennec commented on public/temoignages.json
> +[
Je l'ai mis dans public parce qu'en effet, je le fetch dans le composant temoignages.

2021-02-11 13:48 UTC, tmerlier approved these changes

2021-02-11 13:57 UTC, jdesboeufs approved these changes

2021-02-11 13:57 UTC, merged