Permet la publication de fichier CSV
etalab/adresse.data.gouv.fr pull request #772
Opened 2021-02-08 17:38 UTC by tmerlier

![Capture d’écran 2021-02-08 à 18 36 47](https://user-images.githubusercontent.com/7040549/107258882-9e383d80-6a3c-11eb-96d3-89f6497e7083.png)

2021-02-08 19:22 UTC, jdesboeufs requested changes

2021-02-08 19:22 UTC, jdesboeufs commented on components/bases-locales/validator/file-handler.js
> +                  placeholder='Entrer une url vers un fichier CSV'
On a pas enlevé ça ?

2021-02-08 19:22 UTC, jdesboeufs commented on pages/bases-locales/publication.js
>      <Page>
Retour à Mes Adresses pas pertinent si dépôt de fichier.

2021-02-09 07:37 UTC, tmerlier commented on components/bases-locales/validator/file-handler.js
> +                  placeholder='Entrer une url vers un fichier CSV'
Si… visiblement j'ai raté un rebase.

2021-02-09 08:19 UTC, jdesboeufs commented on components/bases-locales/validator/file-handler.js
> +                  placeholder='Entrer une url vers un fichier CSV'
On peut pas trouver un paramètre plus parlant ? Un boolean ?

2021-02-09 08:19 UTC, jdesboeufs commented
Pense à pousser le changement de config cors aussi

2021-02-09 08:26 UTC, tmerlier commented
La config cors n'est pas utile, l'erreur venait simplement d'un conflit de port sur ma machine.

2021-02-09 09:59 UTC, tmerlier commented
Attendre https://github.com/etalab/adresse.data.gouv.fr-backend/pull/22 avec de merge

2021-02-09 10:05 UTC, jdesboeufs approved these changes

2021-02-09 10:10 UTC, merged