Système de recherche de partenaires
etalab/adresse.data.gouv.fr pull request #795
Opened 2021-04-12 10:34 UTC by Marine-Le-Pennec

- Ajout d'une barre de recherche permettant de trouver les partenaires proposant des outils adaptés à la commune recherchée (recherche par secteur géographique).
- Possibilité d'affiner la recherche par tags
- Le(s) partenaire(s) trouvés s'affiche avec leurs informations détaillées

![Capture d’écran 2021-04-12 à 12 27 08](https://user-images.githubusercontent.com/66621960/114381201-25b04300-9b8b-11eb-9c3b-2147f6e82365.png)

![Capture d’écran 2021-04-12 à 12 27 47](https://user-images.githubusercontent.com/66621960/114381294-411b4e00-9b8b-11eb-800b-16dd232e0e3f.png)

![Capture d’écran 2021-04-12 à 12 26 55](https://user-images.githubusercontent.com/66621960/114381309-45e00200-9b8b-11eb-976a-672df6fd62e1.png)

2021-04-12 12:49 UTC, tmerlier requested changes

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/partner.js
> +function Partner({partnerInfos, isDetailed, isSearched}) {
À retirer, ce n'est pas à ce composant d'adapter son affichage mais plutôt au parent. De plus le nom de cette profs n'a que peu de rapporte avec son objectif final… Ce n'est pas très clair. 

Mais dans tous les cas, le comportement est très bien comme il l'est actuellement, il n'est pas utile d'ajouter .`isSearched`

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/partners.js
> +      {partners && partners.map(partner => {
`partners` n'a pas besoin d'être vérifié car il est indiqué comme `isRequired` dans les `propTypes`. Le composant doit à défaut recevoir un tableau vide.

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +  ]
Ce type de variable est déclarée habituellement en dehors du composant.

Mais `labels` mais pas utile ici. S'il s'agit uniquement d'afficher une majuscule en début de phrase alors un peu de JS ou de CSS fera l'affaire.

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +      console.log('err', err)
Il serait préférable d'afficher cette une erreur à l'utilisateur comme `Impossible d’effectuer la recherche, ressayer ultérieurement.` ou quelque chose dans l'idée.

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +    if (!input) {
else

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +            }} key={label.id} className={selectedLabels.includes(label.id) ? 'label label-active' : 'label'}
Sauter une ligne à chaque props serait plus lisible que de le faire sur cette fonction en une ligne.

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +          border: 1px solid ${theme.colors.lightGrey};
Pas utile.

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/searchbar.js
> +function Searchbar({results, setInput, handleSelect, input, isLoading}) {
Beaucoup de code dupliqué ici sur les `renderX`. Il est nécessaire de réutiliser les composants et d'éviter le plus possible de dupliquer du code.

2021-04-12 12:49 UTC, tmerlier commented on lib/api-geo.js
> +    url += `&fields=${fields}`
Non `fields` est une liste, il ne faut pas modifier cette ligne.

2021-04-12 12:49 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +      const results = await getCommunes({q: input, fields: 'departement', limit: 5, boost: 'population'})
`fields` attend un liste, il faut donc envoyer `fields: ['departement']`

2021-04-12 13:33 UTC, Marine-Le-Pennec commented on components/bases-locales/charte/search.js
> +  ]
J'y ai pensé mais ce n'est pas qu'une question de majuscules. Il y a aussi des histoires de particules et d'apostrophes. Je ne peux pas résoudre ça avec un simple toLowerCase()

2021-04-12 13:38 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +  ]
C'est plus `mise à disposition outils mutualisés` qui n'a pas trop de raison d'être.

2021-04-12 15:39 UTC, tmerlier requested changes

2021-04-12 15:39 UTC, tmerlier commented on components/bases-locales/charte/partners.js
> +  const partners = searchedPartners ? searchedPartners : allPartners
const partners = searchedPartners || allPartners

2021-04-12 15:39 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +      setError(null)
`setError(null)` peut être appelé au début de `handleSearch`.

2021-04-13 12:40 UTC, tmerlier approved these changes

2021-04-13 12:41 UTC, merged