Amélioration de la barre de recherche des partenaires
etalab/adresse.data.gouv.fr pull request #796
Opened 2021-04-14 08:09 UTC by Marine-Le-Pennec

1. - Ajout d'une recherche par code postal 
2. - Amélioration du système de filtrage par tags : 

- Abandon de la liste de tags à remplir manuellement pour une mise à jour automatique de la liste de tags à travers la liste complète des partenaires.
-    Les tags ne correspondant pas au(x) partenaire(s) trouvés sont grisés et le click event est désactivé .
-    La liste de tags n'apparait que lorsque la recherche a aboutie 

![Capture d’écran 2021-04-14 à 10 08 11](https://user-images.githubusercontent.com/66621960/114676177-54ecbe80-9d09-11eb-839e-d6884d6c1b8c.png)

![Capture d’écran 2021-04-14 à 10 08 57](https://user-images.githubusercontent.com/66621960/114676282-6f269c80-9d09-11eb-8180-720caec5389d.png)

![Capture d’écran 2021-04-14 à 10 09 23](https://user-images.githubusercontent.com/66621960/114676340-7e0d4f00-9d09-11eb-9b65-4d2afa86e89b.png)

2021-04-14 12:03 UTC, GllmR approved these changes

2021-04-14 12:19 UTC, tmerlier requested changes

2021-04-14 12:19 UTC, tmerlier commented on components/bases-locales/charte/tags.js
> +    () => {
Pas besoin de retour à la ligne ici.

2021-04-14 12:19 UTC, tmerlier commented on partners.json
> +            "mise à disposition d outils mutualisés"
On a vraiment rien de mieux comme solution ? Là si on doit ajouter un service dans le futur on peut ne peut pas deviner qu'il ne faut pas ajouter les apostrophes.

2021-04-14 12:19 UTC, tmerlier commented on components/bases-locales/charte/tags.js
> +            key={uniqueId()}
Non le tag lui même est sensé être unique pas besoin de générer un id pour ça. Ce genre de méthode est assez coûteuse, a n'utiliser que si c'est nécessaire.

2021-04-14 12:19 UTC, tmerlier commented on components/bases-locales/charte/tags.js
> +    })
Un simple filtre ferait l'affaire.

2021-04-14 12:19 UTC, tmerlier commented on components/bases-locales/charte/tags.js
> +  }, [handleListOfTags])
Pas besoin de useEffect.

2021-04-14 12:19 UTC, tmerlier commented on components/bases-locales/charte/tags.js
> +  const [listOfTags, setListOfTags] = useState([])
Inutile d'utiliser un state pour ça. On peut calculer les tags hors du composant. Une state aurait été utile si jamais la liste des tags pouvait changer.

2021-04-14 12:19 UTC, tmerlier commented on components/bases-locales/charte/search.js
> +        codeDepartement.includes(commune.codeDepartement) || isPerimeterFrance)
Comment sommes nous passé de `commune.departement.code` à `commune.codeDepartement` ?

2021-04-14 12:30 UTC, Marine-Le-Pennec commented on components/bases-locales/charte/search.js
> +        codeDepartement.includes(commune.codeDepartement) || isPerimeterFrance)
Parce qu'en premier lieu, dans ma requête vers l'api, j'ai passé en fileds "departement" pour obtenir le code postal et le nom du département pour l'afficher dans la méthode renderItem. Mais je n'en ai plus besoin maintenant

2021-04-15 08:56 UTC, GllmR commented on components/bases-locales/charte/partner.js
> +    service = service.replace(/’/, ' ')
Tu peux utiliser des `'` dans le `replace` : `service = service.replace('’', ' ')`

2021-04-15 08:58 UTC, GllmR commented on components/bases-locales/charte/search.js
> +      {commune && <Tags onSelectTags={handleSelectedTags} selectedTags={selectedTags} filteredPartners={filteredPartners} allPartners={partners} />}
Mettre les props l'une au dessus de l'autre rendrait la lecture plus clair.

2021-04-16 09:28 UTC, merged