Ajout d'une barre de recherche sur la page listant les Bases adresse locales
etalab/adresse.data.gouv.fr pull request #814
Opened 2021-05-31 15:37 UTC by cedric-famibelle-pronzola

- Création du composant `SearchBAL`
- Ajout du composant à  `components/bases-locales/bases-adresse-locales/index.js`

*capture*
![Capture d’écran du 2021-05-31 17-21-30](https://user-images.githubusercontent.com/45098730/120214390-b2df5200-c234-11eb-8eb3-33272441d3d7.png)

*démo*

https://user-images.githubusercontent.com/45098730/120215399-f8504f00-c235-11eb-81e2-e73f9cc1efcf.mp4

2021-05-31 16:04 UTC, tmerlier requested changes
Le style de `<BanSearch />` étant intégralement repris (erreur compris), il serait préférable de créer un composant `<SearchInput />` par exemple qui reprendrait le style et la logique de base afin de pouvoir être réutilisé.

2021-05-31 16:04 UTC, tmerlier commented on components/bases-locales/bases-adresse-locales/search-bal.js
> +        placeholder='Rechercher une Base adresse locale'
Il serait préférable d'utiliser ce `placeholder` comme un titre pour le champ et de mettre une exemple de recherche en `placeholder`.

2021-06-04 15:17 UTC, GllmR approved these changes

2021-06-07 08:24 UTC, tmerlier approved these changes

2021-06-07 08:26 UTC, merged