Modifcation de l'ordre d'affichage des dernières Base Adresse publiées
etalab/adresse.data.gouv.fr pull request #825
Opened 2021-06-10 15:53 UTC by GllmR

Jusqu'à présent, l'ordre des Bases Adresses Locales n'était pas juste, du fait que certaines Bases Adresses Locales n'ont pas l'attribut `dateMAJ` .
Ces Bases Adresses Locales apparaissaient en haut de la liste, alors qu'elles n'étaient pas les dernières publiées.

Cette PR modifie la façon de trier la liste et permet d'afficher les dernières Bases Adresses Locales publiées en haut de la liste, en séparant les Bases Adresses Locales qui n'ont pas l'attribut `dateMAJ`de celles qui l'ont.

Fix #823

2021-06-14 08:08 UTC, cedric-famibelle-pronzola requested changes

2021-06-14 08:08 UTC, cedric-famibelle-pronzola commented on components/bases-locales/bases-adresse-locales/index.js
> +  )
À mon avis il n'est pas nécessaire de créer un `array` vide pour y pousser des éléments par la suite.
`orderedDatasets` pourrait contenir directement `datasetsWithDateMAJ` et `datasetsWithoutDateMAJ`

2021-06-14 13:35 UTC, cedric-famibelle-pronzola approved these changes

2021-06-14 14:39 UTC, tmerlier requested changes

2021-06-14 14:39 UTC, tmerlier commented on components/bases-locales/bases-adresse-locales/index.js
> +}
Cette méthode pourrait être transformé en `useMemo` avec de gagner un peu en performance lorsque que le filtre est nul.

2021-06-15 15:24 UTC, tmerlier approved these changes

2021-06-15 15:26 UTC, merged