Possibilité de copier les coordonnées GPS
etalab/adresse.data.gouv.fr pull request #826
Opened 2021-06-11 09:55 UTC by cedric-famibelle-pronzola

## - Ajout d'un bouton permettant de copier les coordonnées GPS

*capture desktop*
![adresse-desktop-capture](https://user-images.githubusercontent.com/45098730/121665229-9b139380-caa8-11eb-8d10-234de6e9507c.png)

## - Sur mobile un autre bouton permet d'ouvrir l'application GPS

*capture 1*
![capture_1](https://user-images.githubusercontent.com/45098730/121667639-cb5c3180-caaa-11eb-8662-f5614168357b.jpg)

*capture map*
![capture_2](https://user-images.githubusercontent.com/45098730/121667128-4244fa80-caaa-11eb-8d2c-fcb763b7303b.jpg)

## Captures Vidéos

- Mobile

https://user-images.githubusercontent.com/45098730/121667323-728c9900-caaa-11eb-9020-c4119e4ab8bd.mp4

- Desktop

https://user-images.githubusercontent.com/45098730/121667415-89cb8680-caaa-11eb-90c8-c2d6a3878884.mp4

2021-06-14 12:49 UTC, tmerlier requested changes
Je pense qu'on aurait à gagner à créer une contexte `device` qui s'occuperait de distribuer les props: `isSafariBrowser`, `isMobileDevice` et `viewHeight`

2021-06-14 12:49 UTC, tmerlier commented on components/mapbox/open-gps.js
> +        title='Ouvrir le GPS'
La balise `title` n'existe pas sur les boutons.

2021-06-14 12:49 UTC, tmerlier commented on components/mapbox/open-gps.js
> +        <MapPin size={18} />
L'icon `navigation` serait peut-être plus approprié.

2021-06-14 12:49 UTC, tmerlier commented on components/base-adresse-nationale/numero/coordinates-copy.js
> +  lon: PropTypes.number.isRequired,
On peut regrouper `lat` et `lon` sous le nom `coordinates`, ça évitera d'avoir trop de props inutilement.

Ce commentaire est valable pour tous les composants qui attendent `lat` et `lon`.

2021-06-14 12:49 UTC, tmerlier commented on components/base-adresse-nationale/numero/coordinates-copy.js
> +    }
C'est très javascript vanilla comme technique, autant profiter des avantages de React dans ce genre de situation.

Dans tous les cas je propose d'afficher la notification en haut de l'écran. Celle-ci resterait afficher 5 secondes avant de disparaitre. Elle ferait une largeur max de 250px.

2021-06-14 12:49 UTC, tmerlier commented on components/mapbox/ban-map/index.js
> +  const {lat, lon} = address
Si `address` est `null` alors il faut s'attendre à un crash ici.

2021-06-14 12:49 UTC, tmerlier commented on components/base-adresse-nationale/numero/coordinates-copy.js
> +          Copier la position GPS
L'icon `clipboard` serait la bienvenue ici.

2021-06-14 12:49 UTC, tmerlier commented on components/button.js
> +      <style jsx>{`
Pourquoi ?

2021-06-14 12:49 UTC, tmerlier commented on components/notification.js
> +      {children || message}
Pourquoi ?

2021-06-14 12:54 UTC, cedric-famibelle-pronzola commented on components/notification.js
> +      {children || message}
Avec un long message, l'icône se retrouvait tout en bas de la notification avec l'ancienne configuration

2021-06-14 12:54 UTC, cedric-famibelle-pronzola commented on components/button.js
> +      <style jsx>{`
Un effet de bord grisait les boutons désactivés de la carte au moment de l'apparition de la notification.

2021-06-14 13:06 UTC, tmerlier commented on components/button.js
> +      <style jsx>{`
Tu as vérifier le rendu sur tous les autres boutons du projet ?

2021-06-14 13:22 UTC, cedric-famibelle-pronzola commented on components/button.js
> +      <style jsx>{`
Il est utilisé avec la prop `disabled` ici : 
- `components/bases-locales/publication/authentification.js` (L26)
- `components/bases-locales/publication/form.js` (L73)

J'ai tester le premier (avec ou sans global le résultat est le même) mais pas le 2ème

2021-06-15 14:14 UTC, tmerlier requested changes

2021-06-15 14:14 UTC, tmerlier commented on pages/base-adresse-nationale.js
> +      }}
Ce contexte pu être déplacer dans le score global de l'app afin de permettre le calcule et la réutilisation de certaine de ses `props` comme `isMobile` qui est utilisait à différent niveau du projet ou même `isSafariBrowser` qui pourrait également être utile pour adapter d'autre comportement.

2021-06-18 08:41 UTC, tmerlier requested changes

2021-06-18 08:41 UTC, tmerlier commented on pages/_app.js
> +export const DeviceContext = createContext()
Ce contexte devrait se trouver dans `contexts/device.js`

2021-06-18 08:41 UTC, tmerlier commented on pages/_app.js
> +    setViewHeight(`${window.innerWidth}px`)
`setViewHeight(`${window.innerHeight}px`)`

2021-06-18 14:26 UTC, tmerlier requested changes

2021-06-18 14:26 UTC, tmerlier commented on pages/_app.js
> +  let isSafariBrowser
`isSafariBrowser` devrait être initialisée à `false`.

2021-06-18 14:57 UTC, tmerlier approved these changes

2021-06-18 16:14 UTC, merged