Remplace les notifications par des alertes lors de la copie des coordonées GPS
etalab/adresse.data.gouv.fr pull request #837
Opened 2021-06-18 17:22 UTC by cedric-famibelle-pronzola

- Ajout de la fonction `onClose` lors de la fin du `timeout` dans le composant `Alert`
- Composant `Alert` remplace le composant `Notification` lors de la copie des coordonnées GPS

*capture avant*
![gps-before](https://user-images.githubusercontent.com/45098730/122596428-22917180-d06a-11eb-85ea-198e8329d100.png)

*capture après*
![gps-after](https://user-images.githubusercontent.com/45098730/122596446-2cb37000-d06a-11eb-9186-7a6681973348.png)

2021-06-25 08:09 UTC, GllmR approved these changes

2021-06-28 08:12 UTC, tmerlier requested changes

2021-06-28 08:12 UTC, tmerlier commented on components/alert.js
> +  }
```
  if (!alertRoot || !document) {
    return null
  }
```

2021-06-28 08:12 UTC, tmerlier commented on components/base-adresse-nationale/numero/index.js
> +          duration={10000}
Bien que la durée soit de 10sec, l'alerte semble disparaitre après seulement 5sec (temps par défaut).

2021-06-28 08:20 UTC, tmerlier commented on components/base-adresse-nationale/numero/index.js
> +          duration={10000}
Aucun problème, je me suis simplement trompé de notification.

2021-06-28 08:24 UTC, tmerlier approved these changes

2021-06-28 08:24 UTC, merged